---
- hosts: test_srv
  vars:
    - user: "{{ ansible_env.USER }}"
  pre_tasks:
    - name: Printing all the environment variables in Ansible
      debug:
        msg: "{{ ansible_env }}"
  roles:
    - common
    # - gpu
