- name: Include nvidia driver
  include_role:
    name: nvidia.nvidia_driver
    apply:
      become: yes
  vars:
    nvidia_driver_ubuntu_install_from_cuda_repo: yes
    nvidia_driver_ubuntu_branch: 460

- name: Install nvtop for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'
